name: build-trm

on:
  push:
  schedule:
    - cron: "0 2 * * *"
  pull_request:
  workflow_dispatch:

jobs:
  build-trm:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: "Prepare"
        run: |
          sudo apt update
          sudo apt install -y python3-sphinx texlive-full texlive-xetex texlive-latex-recommended texlive-latex-extra latexmk
          mkdir -p ${GITHUB_WORKSPACE}/artifacts/

      - name: "Compile TRM for SG200X"
        run: |
          cd SG200X/TRM && bash build.sh
          cp -av out/*.pdf ${GITHUB_WORKSPACE}/artifacts/

      - name: "Compile TRM for SG2042"
        run: |
          build_tiemstamp=$(date "+%Y%m%d%H%M")
          cd SG2042/TRM && make latexpdf
          cp -av build/latex/sg2042technicalreferencemanual.pdf \
            ${GITHUB_WORKSPACE}/artifacts/SG2042TechnicalReferenceManual_${build_tiemstamp}.pdf

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: TechnicalReferenceManual
          path: artifacts/*.pdf
          retention-days: 60
